### PR TITLE
Auto-Comment on Raise new Issues

### LINKED ISSUE #13: 🔄 Add Workflow File for Auto-Commit on Open Issues
## Description:

I propose adding a workflow file to the repository that automatically commits changes when a new issue is opened. This automation will streamline the development process and ensure timely updates.

## Issue Details:

- 📝 Manual Commits: Currently, commits must be made manually when an issue is opened, which can be time-consuming and prone to delays.
- ⚙️ Automation: Implementing an automated workflow will enhance efficiency and consistency.

## Screenshots-

image

## Benefits:

- ⏱️ Time-Saving: Automates repetitive tasks, saving valuable time for contributors and maintainers.
- 🔄 Consistency: Ensures that all issues are promptly followed by the necessary commits, maintaining a consistent update process.
- 📈 Improved Workflow: Enhances the overall workflow by reducing manual steps and potential human errors.

@avinashkranjan  please assign this issues to me

### PR DESCRIPTION
**Pull request by mdazfar2**
## Description
I'm excited to submit this pull request to introduce a new workflow file that automates the commit process whenever a new issue is opened. This enhancement is designed to streamline our development process and ensure timely updates.

### Issues
Fixes #13  

## Benefits:

- ⏱️ Time-Saving: Automates repetitive tasks, saving valuable time for contributors and maintainers.
- 🔄 Consistency: Ensures that all issues are promptly followed by the necessary commits, maintaining a consistent update process.
- 📈 Improved Workflow: Enhances the overall workflow by reducing manual steps and potential human errors.

@avinashkranjan I hope you would be love it.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@mdazfar2 Please resolve the unresolved [sourcery-ai](https://github.com/apps/sourcery-ai) suggestions

**Comment by mdazfar2** [comment]
@avinashkranjan believe me it is workable i will create pull request after Handson.

**Comment by avinashkranjan** [comment]
[sourcery-ai](https://github.com/apps/sourcery-ai) has asked to update the way it's written to make it more readable, kindly make the changes as asked, You haven't made the changes and yet you have resolved, It's not about the working. Kindly read what the changes that has been asked.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
