### PR TITLE
Add New Documentation Template to Issues Template

### LINKED ISSUE #12: Add New Template for Documentation in Issues Template
## Description:

I propose adding a new template specifically for documentation-related issues to the Issues Template of the logsuite repository. This will help streamline and standardize the process of reporting and addressing documentation needs.

## Screnshots
New feature screenshot

<br/>

Here are the above this is just a screenshot while raising new `new issues`

- & When users click on `Get Started` it is showing option like the below screenshot-

image

@avinashkranjan  Looking forward to your feedback and the opportunity to contribute to this enhancement.

### PR DESCRIPTION
**Pull request by mdazfar2**
## Description-

This pull request adds a new template for documentation in the ISSUES TEMPLATE section. The goal is to provide a standardized format for reporting and addressing documentation-related issues, ensuring clarity and consistency across our project.

## Issues FIx
#12 

## How to Use?
- **Navigate to the Issues section:** Click on 'New Issue' and select the 'Documentation' template.
- **Fill in the required fields**: Provide a detailed description, specify the affected documentation, and suggest possible improvements.
- **Submit the issue**: Once all fields are filled out, submit the issue for review.

@avinashkranjan  I appreciate your consideration and look forward to your feedback.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@mdazfar2 Kindly make the changes requested by [sourcery-ai](https://github.com/apps/sourcery-ai)

**Comment by mdazfar2** [comment]
Same thing i write `workflow` file on my own repo and it is working fine. @avinashkranjan

**Comment by avinashkranjan** [comment]
> Same thing i write `workflow` file on my own repo and it is working fine. @avinashkranjan you should have to merge
> 
> * mark as resolved ✔️

[sourcery-ai](https://github.com/apps/sourcery-ai) has marked same changes in the documentation, You haven't made the changes and yet you have resolved, It's not about the working. Kindly read what the changes that has been asked.

**Comment by mdazfar2** [comment]
@avinashkranjan Hope all is well in this PR please check once.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
