### PR TITLE
Created About Us page and Contact us page alongwith navbar and footer

### LINKED ISSUE #47: Create an attractive separate About Us and Contact Us Page
**Is your feature request related to a problem? Please describe.**

There is no about us page or contact us page

**Describe the solution you'd like**

There should be a separate and attractive, dedicated About Us Page and Contact Us page 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by r1shayanr7**
## Description

Created About Us and Contact Us Page

Created Navbar and Footer

Added blur, transparency effects and interactive animations

Added Dark mode for all pages

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/d052889b-3746-4cf4-97bb-4c18290c34c2

## Additional context

Add any other context or screenshots about the pull request here.

## Summary by Sourcery

This pull request introduces new 'About Us' and 'Contact Us' pages, along with a new Navbar and Footer. It also adds dark mode support and various UI enhancements, including blur and transparency effects. Additionally, it fixes a minor issue in the mode toggle button and updates the Next.js configuration for image loading.

- **New Features**:
    - Created 'About Us' and 'Contact Us' pages with detailed content and animations.
    - Implemented a new Navbar and Footer for site-wide navigation and information.
    - Added dark mode support across all pages for better user experience.
- **Bug Fixes**:
    - Fixed a minor issue in the mode toggle button's Moon icon class.
- **Enhancements**:
    - Introduced blur, transparency effects, and interactive animations to improve UI aesthetics.
    - Updated the 'Home' page to integrate the new Navbar and Footer components.
- **Build**:
    - Configured Next.js to allow loading images from 'dummyimage.com'.

### CODE REVIEW

**Comment by r1shayanr7** [comment]
If there's a problem while merging this pr, then inform me, I will fix these errors and raise a new pr

**Comment by r1shayanr7** [comment]
@avinashkranjan kindly look into my pr and merge it if it aligns with your expectations

**Comment by avinashkranjan** [comment]
@r7projects-shayan Will Review the PR in 1 - 2 Days

**Comment by r1shayanr7** [comment]
@avinashkranjan Sir, kindly review and merge the PR

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
