### PR TITLE
Implement Workflow for Auto-Commit on Issue Closure

### LINKED ISSUE #13: 🔄 Add Workflow File for Auto-Commit on Open Issues
## Description:

I propose adding a workflow file to the repository that automatically commits changes when a new issue is opened. This automation will streamline the development process and ensure timely updates.

## Issue Details:

- 📝 Manual Commits: Currently, commits must be made manually when an issue is opened, which can be time-consuming and prone to delays.
- ⚙️ Automation: Implementing an automated workflow will enhance efficiency and consistency.

## Screenshots-

image

## Benefits:

- ⏱️ Time-Saving: Automates repetitive tasks, saving valuable time for contributors and maintainers.
- 🔄 Consistency: Ensures that all issues are promptly followed by the necessary commits, maintaining a consistent update process.
- 📈 Improved Workflow: Enhances the overall workflow by reducing manual steps and potential human errors.

@avinashkranjan  please assign this issues to me

### PR DESCRIPTION
**Pull request by mdazfar2**
## Description:

I'm thrilled to submit this pull request introducing a new workflow that automates the commit process upon issue closure. This enhancement streamlines our development workflow, ensuring that changes are recorded promptly and accurately.

## Usable
When the issues will close by you then the `github-actions` will automatic comment for issues close `paragraph`

@avinashkranjan Thank you for considering this enhancement. I eagerly await your feedback.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Hey @mdazfar2, Please make changes as suggested by [sourcery-ai](https://github.com/apps/sourcery-ai)

**Comment by mdazfar2** [comment]
@avinashkranjan believe me, it is fully functional. I will create a pull request after hands-on.

**Comment by avinashkranjan** [comment]
[sourcery-ai](https://github.com/apps/sourcery-ai) It's for fail safe, kindly make the changes as asked, You haven't made the changes and yet you have resolved, It's not about the working. Kindly read what the changes that has been asked.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
